import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";

export default function Home({ items }) {
  const editorArray = [];
  const pushArray = [];

  items.filter((item) => {
    if (item.source === "Editor") {
      editorArray.push(item);
    } else if (item.source === "Push") {
      pushArray.push(item);
    }
  });

  let editorTable = editorArray.slice(0, 5);
  let pushTable = pushArray.slice(0, 5);
  return (
    <div className="container">
      <Head>
        <title>Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <div>
          <h2>
            No of Records with value – “Push” :{" "}
            <span className="num">{pushArray.length}</span>
          </h2>
          <div className="table">
            <div className="table-row table-head">
              <h3 className="table-cell">Type</h3>
              <h3 className="table-cell">Headline</h3>
            </div>
            {pushTable.map((tableRow) => (
              <div key={tableRow._id} className="table-row">
                <p className="table-cell">{tableRow.type}</p>
                <p className="table-cell">{tableRow.headline}</p>
              </div>
            ))}
          </div>
        </div>
        <div style={{ marginTop: "2rem" }}>
          <h2>
            No of Records with value – “Editor” :{" "}
            <span className="num">{editorArray.length}</span>
          </h2>
          <div className="table">
            <div className="table-row table-head">
              <h3 className="table-cell">Type</h3>
              <h3 className="table-cell">Headline</h3>
            </div>
            {editorTable.map((tableRow) => (
              <div key={tableRow._id} className="table-row">
                <p className="table-cell">{tableRow.type}</p>
                <p className="table-cell">{tableRow.headline}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://18.136.165.153:9000/search");
  const items = await res.json();

  return {
    props: {
      items: items.listItem,
    },
    revalidate: 10,
  };
}
